apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password123
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
            - name: productdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: ebs-pvc
        
        - name: productdb
          configMap:
            name: productdb
